// File generated by FlutterFire CLI + An Đồ flavor wiring.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static const databaseURL =
      'https://fir-integration-4405d-default-rtdb.asia-southeast1.firebasedatabase.app';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured for An Đồ 1.0.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Android in 1.0.',
        );
    }
  }

  /// Production flavor: com.hoangluan.safetymap
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGhrixc7t7moLVGfBDTR-1OqKGN8LUoWI',
    appId: '1:893533751647:android:1ec0987093fd2e14f64eea',
    messagingSenderId: '893533751647',
    projectId: 'fir-integration-4405d',
    storageBucket: 'fir-integration-4405d.firebasestorage.app',
    databaseURL: databaseURL,
  );

  /// Dev flavor: com.hoangluan.safetymap.dev
  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyAGhrixc7t7moLVGfBDTR-1OqKGN8LUoWI',
    appId: '1:893533751647:android:cc19dafbe837e8f6f64eea',
    messagingSenderId: '893533751647',
    projectId: 'fir-integration-4405d',
    storageBucket: 'fir-integration-4405d.firebasestorage.app',
    databaseURL: databaseURL,
  );

  static FirebaseOptions androidForPackageName(String packageName) {
    if (packageName.endsWith('.dev')) return androidDev;
    return android;
  }
}
